/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-10-22 19:45:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/bizwork/workspace/Project_Peace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_peace/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/bizwork/workspace/Project_Peace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_peace/WEB-INF/lib/spring-webmvc-5.2.8.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1595286666000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.8.RELEASE.jar", Long.valueOf(1598357002141L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598357003574L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/nav.css?ver=2020-10-12-002\" />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://kit.fontawesome.com/2d323a629b.js\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.2.0.min.js\" ></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/nav.js?ver=2020-10-12-002\" defer></script>\r\n");
      out.write("    <title>마이페이지 입니다</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("   @charset \"UTF-8\";\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html,\r\n");
      out.write("body {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  width: 20%;\r\n");
      out.write("  text-align: right;\r\n");
      out.write("  margin: 8px 140px;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  color: black;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  width: 30%;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  border: 1px solid navy;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#btn_box {\r\n");
      out.write("  text-align: right;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  margin:10px 90px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_box button {\r\n");
      out.write("  padding: 8px 12px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  color: black;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  text-align: right;\r\n");
      out.write("  margin:15px 5px ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_box button:first-child {\r\n");
      out.write("  background-color:skyblue;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_box button:last-child {\r\n");
      out.write("  background-color: black;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_box button:first-child:hover {\r\n");
      out.write("  background-color:lightseagreen;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_box button:last-child:hover {\r\n");
      out.write("  background-color: gray;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".banner-area {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 500px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50px;\r\n");
      out.write("    background-image: url(static/images/Ybook.jpg);\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-position: center center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .banner-area h3 {\r\n");
      out.write("    padding-top: 8%;\r\n");
      out.write("    font-size: 60px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    color: black;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .content-area {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    top: 450px;\r\n");
      out.write("    background: #ddd;\r\n");
      out.write("    height: 1500px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .content-area h4 {\r\n");
      out.write("    letter-spacing: 4px;\r\n");
      out.write("    padding-top: 30px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .content-area p {\r\n");
      out.write("    padding: 2% 0;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("  <script>\r\n");
      out.write(" /*  $(document).ready(function(){\r\n");
      out.write("\t\t// 회원 탈퇴 누르면 이동하는 창 ... 수정 필요\r\n");
      out.write("\t\t$(\"div#btn-delete\").on(\"click\", function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(\"정말 탈퇴하시겠습니까?\");\r\n");
      out.write("\t\t\tdocument.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memberDelete\";\r\n");
      out.write("\t\t\t\t\t    \r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("  }) */\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \tdocument.getElementById(\"btn-delete\")[0].click();\r\n");
      out.write("  </script>\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("      <div class=\"navbar__logo\">\r\n");
      out.write("        <i class=\"fab fa-accusoft\"></i>\r\n");
      out.write("        <a href=\"\">SHORT NAVI</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar__menu\">\r\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Home</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage\">MyPage</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Logout</a></li>\r\n");
      out.write("        <li><a href=\"\">Contact Us</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar__icons\">\r\n");
      out.write("        <li><i class=\"fab fa-twitter\"></i></li>\r\n");
      out.write("        <li><i class=\"fab fa-facebook-f\"></i></li>\r\n");
      out.write("        <li><i class=\"fab fa-google\"></i></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"#\" class=\"navbar__toggleBtn\">\r\n");
      out.write("        <i class=\"fas fa-bars\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div id=\"page\">\r\n");
      out.write("      \r\n");
      out.write("<header>\r\n");
      out.write("  <div class=\"banner-area\">\r\n");
      out.write("    <h3>MY PAGE</h3>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"content-area\">\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <h4>Content</h4>\r\n");
      out.write("       \r\n");
      out.write(" \t<div><label>아이디</label><input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN.n_userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></div>\r\n");
      out.write(" \t<div><label>현재password</label><input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN.n_password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></div>\r\n");
      out.write(" \t<div><label>변경할password</label><input value=\"1234\" /></div>\r\n");
      out.write(" \t\r\n");
      out.write("      <div><label>이메일</label><input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN.n_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></div>\r\n");
      out.write("      <div><label>가입일</label><input value=\"2020-10-16\" name=\"p_dcode\" ></div>\r\n");
      out.write("\t\r\n");
      out.write("      <div>\r\n");
      out.write("        <label>프로필사진</label\r\n");
      out.write("        ><input path=\"p_image\" type=\"file\" name=\"p_image\" id=\"p_image\" />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"btn_box\">\r\n");
      out.write("        <button type=\"button\" id=\"btn-update\">수정 완료</button>\r\n");
      out.write("        <button type=\"button\" id=\"btn-delete\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memberDelete/\">회원 탈퇴</a></button>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </header>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/mypage.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("rootPath");
      // /WEB-INF/views/mypage.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mypage.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
